name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: appimagetool
      run: |
        set -x
        cd ../

        #wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        #wget -q https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-833-x86_64.AppImage -O appimagetool-x86_64.AppImage

        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        pwd; ls -lah

    - name: Make AppImage
      run: |
        set -x
        version_IrfanView="4.72"
        rm -rv .git/ .github/

        cd ../
        #ARCH=x86_64 ./appimagetool-x86_64.AppImage IrfanView_AppImage/
        ARCH=x86_64 VERSION="${version_IrfanView}-1_JB" ./appimagetool-x86_64.AppImage IrfanView_AppImage/
        pwd; ls -lah

        fileName=$(ls IrfanView*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"

        pwd; ls -lah
        mv IrfanView*.AppImage IrfanView*.zsync IrfanView*.md5 IrfanView_AppImage/

    - uses: xresloader/upload-to-github-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "IrfanView*.AppImage; IrfanView*.zsync; IrfanView*.md5"
        release_id: ${{ steps.create_release.outputs.id }}
        verbose: true
        draft: false
        default_release_name: "IrfanView V in AppImage"
